---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: opensuse-12.3
    driver_config:
      box: opensuse-12.3-64
      box_url: http://sourceforge.net/projects/opensusevagrant/files/12.3/opensuse-12.3-64.box/download
      require_chef_omnibus: true
  - name: centos-6.5
  - name: fedora-20
#  - name: debian-7.0
#  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[stow::default]
    attributes:
