source "https://rubygems.org"

gem 'berkshelf', '~> 3.0'
gem 'chef', '~> 12.4'

group :test do
  gem 'chefspec-coveragereports'
  gem 'rake'
  gem 'foodcritic'
  gem 'rubocop'
end

group :development do
  gem 'stove'
end
