source "https://rubygems.org"

gem 'berkshelf', '~> 3.0'
gem 'chef', '~> 12.4'

group :test do
  gem 'rake'
  gem 'foodcritic'
  gem 'rubocop'
  gem 'coveralls',  require: false
end

group :development do
  gem 'stove'
end
